### PR TITLE
Tnw clone

### PR DESCRIPTION
**Pull request by abeidahmed**
- Make use of the `BEM` naming convention.
- Fully responsive website with 2 `media queries`.
- Extracted `classes` as much as possible for reusability.

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @abeidahmed  & @Murodjon000 **

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 


### Navbar:

- [x] the navbar looks great and responsive as it should be. but please note that the search icon on the original page is inverted

**clone**
fdsgedfg

**original**
dsfsdf


### Latest news section:

- [x] it looks great, but the images look a little stretched in the small screen size. to avoid that, you can use the `object-fit: cover;`  property on these images.

### Latest funding section:

- [x] the images in this section are way bigger than the original page. please make sure to fix this issue 

**clone**


**original**


### Latest deals section:

- [x] it looks great, but the images look a little stretched in the small screen size. to avoid that, you can use the `object-fit: cover;`  property on these images.


---

Overall, the project looks fantastic. but, with some tweaks,  it can look better than the original one 👍.

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @abeidahmed  & @Murodjon000**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] you have implemented most of the required changes, bit you didn't implement the Latest funding section one's. please go back and do these changes.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by abeidahmed** [comment]
> ### Changes required ♻️
> **Hello @abeidahmed & @Murodjon000**
> 
> Great job with the project so far it looks amazing, but there are still some changes to be made:
> 
> ### Requested 🔴
> * [x]  you have implemented most of the required changes, bit you didn't implement the Latest funding section one's. please go back and do these changes.
> 
> please make these changes and request another code review.
> 
> if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

The latest funding section looks fine on my partner's computer and on mine. The screenshot that you posted isn't what we are seeing. This is what we are seeing (the screenshot is taken from the live page which is hosted [here](https://abeidahmed.github.io/tnw-clone/)
2020-12-01 19_38_15-TNW clone

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @abeidahmed  & @Murodjon000**

**Sorry for the conflict, the page looks different on different pages and browsers. For now, the project is approved, you can go ahead and merge this pull request**

**Comment by abeidahmed** [comment]
> ### STATUS: APPROVED ✔️ ✔️
> **hi @abeidahmed & @Murodjon000**
> 
> **Sorry for the conflict, the page looks different on different pages and browsers. For now, the project is approved, you can go ahead and merge this pull request**

Thanks for taking all the trouble. Although the project is approved, we'll still try to find the actual culprit to the problem. 
Many thanks!

**Review by layzrd — APPROVED** [review]
### Status: Approved 🙌 🎇
Hi @abeidahmed and @Murodjon000, Congratulations 🎊 👏, you did very well on this project. I appreciate your detail-oriented view.

Now, you can move ahead.

Please don't forget to merge to master. Good luck with the next projects!

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Pull request merged**
